const STORAGE_KEY = "speakup180.state.v2";
const CUSTOM_DATA_KEY = "speakup180.curriculum.v2";
const ACTIVE_PROFILE_KEY = "speakup180.activeProfile.v1";
const SUPABASE_URL = "https://hmnmedoxqhiyzwmvyhlt.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6Imhtbm1lZG94cWhpeXp3bXZ5aGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwMDE3NjQsImV4cCI6MjA5NTU3Nzc2NH0.AmhG2WKv3PDqoft95Oojz32adZAt0nbDa4wEu9aHiWw".replace("JIUzI1Ni", "UzI1Ni");
const PROFILES = ["zotinking", "viridiansky"];
const READ_SECONDS = 300;
const FOCUS_SECONDS = 1500;
const topics = ["아침 루틴", "출근 준비", "회사 대화", "점심 시간", "카페 주문", "길 묻기", "전화 응대", "약속 잡기", "쇼핑", "운동", "건강", "가족", "친구", "여행", "공항", "호텔", "식당", "문제 해결", "감정 표현", "의견 말하기", "회의", "이메일", "취미", "주말", "집안일", "은행", "병원", "날씨", "학습", "목표 관리"];
const situations = [["in the morning", "아침에", "아침에"], ["before work", "출근 전에", "일 전에"], ["at the office", "회사에서", "사무실에서"], ["during lunch", "점심시간에", "점심 동안에"], ["at a cafe", "카페에서", "카페에서"], ["on the street", "길에서", "거리 위에서"], ["on the phone", "전화로", "전화 위에서"], ["after work", "퇴근 후에", "일 후에"], ["at the store", "가게에서", "가게에서"], ["at the gym", "헬스장에서", "체육관에서"], ["when I feel tired", "피곤할 때", "내가 피곤하다고 느낄 때"], ["with my family", "가족과 함께", "나의 가족과 함께"], ["with my friends", "친구들과 함께", "나의 친구들과 함께"], ["when I travel", "여행할 때", "내가 여행할 때"], ["at the airport", "공항에서", "공항에서"], ["at the hotel", "호텔에서", "호텔에서"], ["at the restaurant", "식당에서", "식당에서"], ["when something goes wrong", "문제가 생겼을 때", "무언가가 잘못될 때"], ["when I am nervous", "긴장될 때", "내가 긴장되어 있을 때"], ["in my opinion", "내 생각에는", "나의 의견 안에서"], ["in the meeting", "회의에서", "회의 안에서"], ["by email", "이메일로", "이메일에 의해"], ["in my free time", "자유 시간에", "나의 자유 시간에"], ["on the weekend", "주말에", "주말에"], ["at home", "집에서", "집에서"], ["at the bank", "은행에서", "은행에서"], ["at the clinic", "병원에서", "진료소에서"], ["on rainy days", "비 오는 날에", "비 오는 날들에"], ["when I study English", "영어를 공부할 때", "내가 영어를 공부할 때"], ["this month", "이번 달에", "이번 달에"]];
const actions = [["drink some water", "물을 마셔요", "마셔요 약간의 물을"], ["check my schedule", "일정을 확인해요", "확인해요 나의 일정을"], ["send a quick message", "짧은 메시지를 보내요", "보내요 빠른 메시지를"], ["ask one more question", "질문을 하나 더 해요", "물어요 하나 더 질문을"], ["take a short break", "잠깐 쉬어요", "가져요 짧은 휴식을"], ["make a simple plan", "간단한 계획을 세워요", "만들어요 간단한 계획을"], ["look for a better option", "더 나은 선택지를 찾아요", "찾아요 더 나은 선택지를"], ["say it one more time", "그 말을 한 번 더 해요", "말해요 그것을 한 번 더"], ["practice out loud", "소리 내어 연습해요", "연습해요 소리 내어"], ["write it down", "그것을 적어요", "적어요 그것을"], ["order something light", "가벼운 것을 주문해요", "주문해요 무언가 가벼운 것을"], ["find the right place", "맞는 장소를 찾아요", "찾아요 맞는 장소를"], ["explain the situation", "상황을 설명해요", "설명해요 그 상황을"], ["make a reservation", "예약을 해요", "만들어요 예약을"], ["change my plan", "계획을 바꿔요", "바꿔요 나의 계획을"], ["start with an easy sentence", "쉬운 문장으로 시작해요", "시작해요 쉬운 문장으로"], ["repeat the same sentence", "같은 문장을 반복해요", "반복해요 같은 문장을"], ["speak more slowly", "더 천천히 말해요", "말해요 더 천천히"], ["tell you what happened", "무슨 일이 있었는지 말해요", "말해요 당신에게 무엇이 일어났는지"], ["choose the safer way", "더 안전한 방법을 선택해요", "선택해요 더 안전한 방법을"]];
const chatGptPrompt = `너는 영어 회화 커리큘럼 디자이너야. SpeakUp 180 앱에 넣을 180일 x 하루 10문장 JSON을 만들어줘. 대상은 영어 공부에 실패했던 한국인 직장인이야. english, hint, korean, level 필드를 사용하고, hint는 한국어 자연어순이 아니라 영어 어순에 맞춘 한글 힌트로 써줘. 초반 60일은 A1, 중반 60일은 A2, 후반 60일은 B1로 만들어줘. JSON 외 설명은 쓰지 마.`;
const state = { view: "routine", profile: localStorage.getItem(ACTIVE_PROFILE_KEY) || "", profileReady: false, day: 1, step: "sound", flash: 0, reveal: false, read: READ_SECONDS, readRun: false, focus: FOCUS_SECONDS, focusRun: false, status: "", importStatus: "", syncStatus: "클라우드 연결 준비 중", progress: { completedDays: [], readDone: {}, recallDone: {}, checkedSentences: {} }, curriculum: [] };
let readTimer = null;
let focusTimer = null;
let saveTimer = null;
let loadingCloud = false;
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? "").replace(/[&<>"]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[m]));
const safe = (v) => { try { return v ? JSON.parse(v) : null; } catch { return null; } };
const clamp = (n, a, b) => Math.max(a, Math.min(b, Number(n) || a));
const dayKey = (d = state.day) => `day-${d}`;
const profileKey = (base) => `${base}.${state.profile}`;
const formatTime = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;
function buildCurriculum() { return Array.from({ length: 180 }, (_, i) => { const day = i + 1, sit = situations[i % situations.length], level = day <= 60 ? "A1" : day <= 120 ? "A2" : "B1"; const patterns = [(a) => [`I usually ${a[0]} ${sit[0]}.`, `나는 보통 ${sit[1]} ${a[1]}.`, `나는 보통 ${a[2]} / ${sit[2]}`], (a) => [`Can I ${a[0]} ${sit[0]}?`, `${sit[1]} ${a[1]}도 될까요?`, `할 수 있나요 내가 ${a[2]} / ${sit[2]}`], (a) => [`I need to ${a[0]} ${sit[0]}.`, `나는 ${sit[1]} ${a[1]}해야 해요.`, `나는 필요해요 ${a[2]}하는 것이 / ${sit[2]}`], (a) => [`Could you help me ${a[0]} ${sit[0]}?`, `${sit[1]} ${a[1]}하는 걸 도와주실 수 있나요?`, `해주실 수 있나요 당신이 도와주는 것을 / 내가 ${a[2]}하게 / ${sit[2]}`], (a) => [`I am trying to ${a[0]} ${sit[0]}.`, `나는 ${sit[1]} ${a[1]}하려고 하고 있어요.`, `나는 노력하고 있어요 ${a[2]}하려고 / ${sit[2]}`], () => [`What should I do ${sit[0]}?`, `${sit[1]} 나는 무엇을 해야 하나요?`, `무엇을 해야 하나요 내가 / ${sit[2]}`], (a) => [`I do not have time to ${a[0]} ${sit[0]}.`, `나는 ${sit[1]} ${a[1]}할 시간이 없어요.`, `나는 가지고 있지 않아요 시간을 / ${a[2]}할 / ${sit[2]}`], (a) => [`It is hard for me to ${a[0]} ${sit[0]}.`, `나는 ${sit[1]} ${a[1]}하는 게 어려워요.`, `그것은 어려워요 나에게 / ${a[2]}하는 것이 / ${sit[2]}`], (a) => [`I feel better when I ${a[0]} ${sit[0]}.`, `${sit[1]} ${a[1]}하면 기분이 나아져요.`, `나는 느껴요 더 낫게 / 내가 ${a[2]}할 때 / ${sit[2]}`], (a) => [`Would you like to ${a[0]} ${sit[0]}?`, `${sit[1]} ${a[1]}하고 싶으세요?`, `원하시나요 당신은 ${a[2]}하기를 / ${sit[2]}`]]; return { day, topic: topics[i % topics.length], title: `${day}일차 · ${topics[i % topics.length]}`, sentences: patterns.map((p, n) => { const a = actions[(day * 7 + n * 3) % actions.length], r = p(a); return { id: `d${day}-s${n + 1}`, english: r[0], korean: r[1], hint: r[2], level }; }) }; }); }
function validateCurriculum(data) { const days = Array.isArray(data) ? data : data?.days; if (!Array.isArray(days) || days.length !== 180) return null; const normalized = days.map((d, i) => ({ day: Number(d.day) || i + 1, topic: String(d.topic || "커스텀 문장"), title: `${Number(d.day) || i + 1}일차 · ${d.topic || "커스텀 문장"}`, sentences: (d.sentences || []).slice(0, 10).map((s, j) => ({ id: `c${i + 1}-s${j + 1}`, english: String(s.english || "").trim(), hint: String(s.hint || s.korean || "").trim(), korean: String(s.korean || "").trim(), level: String(s.level || "") })) })); return normalized.every((d) => d.sentences.length === 10 && d.sentences.every((s) => s.english && s.hint)) ? normalized : null; }
function headers(extra = {}) { return { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`, "Content-Type": "application/json", ...extra }; }
async function supabase(path, options = {}) { const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, { ...options, headers: headers(options.headers || {}) }); if (!res.ok) throw new Error((await res.text()) || `Supabase ${res.status}`); return res.status === 204 ? null : res.json(); }
function currentDay() { return state.curriculum[state.day - 1]; }
function reviewDays() { return state.curriculum.filter((d) => d.day >= Math.max(1, state.day - 5) && d.day <= state.day); }
function doneRead(d = state.day) { return Boolean(state.progress.readDone[dayKey(d)]); }
function recallCount(d = state.day) { return (state.progress.recallDone[dayKey(d)] || []).length; }
function checkedCount(d = state.day) { return (state.progress.checkedSentences[dayKey(d)] || []).length; }
function completedCount() { return new Set(state.progress.completedDays).size; }
function isChecked(id) { return (state.progress.checkedSentences[dayKey()] || []).includes(id); }
function isRecall(id) { return (state.progress.recallDone[dayKey()] || []).includes(id); }
function loadLocal() { const saved = safe(localStorage.getItem(profileKey(STORAGE_KEY))); state.curriculum = validateCurriculum(safe(localStorage.getItem(profileKey(CUSTOM_DATA_KEY)))) || buildCurriculum(); if (saved) { state.day = clamp(saved.day, 1, 180); state.progress = { completedDays: saved.completedDays || [], readDone: saved.readDone || {}, recallDone: saved.recallDone || {}, checkedSentences: saved.checkedSentences || {} }; } state.read = doneRead() ? 0 : READ_SECONDS; state.step = doneRead() ? "recall" : "sound"; }
function saveLocal() { if (!state.profile) return; localStorage.setItem(ACTIVE_PROFILE_KEY, state.profile); localStorage.setItem(profileKey(STORAGE_KEY), JSON.stringify({ day: state.day, ...state.progress })); if (!loadingCloud) { clearTimeout(saveTimer); saveTimer = setTimeout(saveCloud, 500); } }
async function loadCloud() { loadingCloud = true; state.syncStatus = `${state.profile} 불러오는 중`; render(); try { const p = await supabase(`speakup_progress?profile_id=eq.${state.profile}&select=*`); if (p?.[0]) { state.day = clamp(p[0].current_day, 1, 180); state.progress = { completedDays: p[0].completed_days || [], readDone: p[0].read_done || {}, recallDone: p[0].recall_done || {}, checkedSentences: p[0].checked_sentences || {} }; } const c = await supabase(`speakup_curriculums?profile_id=eq.${state.profile}&select=days`); const cloudDays = validateCurriculum(c?.[0]?.days); if (cloudDays) { state.curriculum = cloudDays; localStorage.setItem(profileKey(CUSTOM_DATA_KEY), JSON.stringify({ days: cloudDays })); } state.syncStatus = `${state.profile} 동기화 완료`; localStorage.setItem(profileKey(STORAGE_KEY), JSON.stringify({ day: state.day, ...state.progress })); } catch (e) { state.syncStatus = `동기화 실패: ${e.message.slice(0, 70)}`; } finally { loadingCloud = false; render(); } }
async function saveCloud() { try { await supabase("speakup_progress?on_conflict=profile_id", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=minimal" }, body: JSON.stringify({ profile_id: state.profile, current_day: state.day, completed_days: state.progress.completedDays, read_done: state.progress.readDone, recall_done: state.progress.recallDone, checked_sentences: state.progress.checkedSentences }) }); state.syncStatus = `${state.profile} 저장됨`; render(); } catch (e) { state.syncStatus = `저장 실패: ${e.message.slice(0, 70)}`; render(); } }
async function saveCurriculumCloud() { try { await supabase("speakup_curriculums?on_conflict=profile_id", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=minimal" }, body: JSON.stringify({ profile_id: state.profile, title: "SpeakUp 180 Custom Curriculum", days: state.curriculum }) }); state.importStatus = `${state.profile} 커리큘럼을 Supabase에 저장했습니다.`; } catch (e) { state.importStatus = `커리큘럼 저장 실패: ${e.message.slice(0, 70)}`; } render(); }
function chooseProfile(profile) { if (!PROFILES.includes(profile)) return; state.profile = profile; state.profileReady = true; state.view = "routine"; state.status = ""; state.importStatus = ""; localStorage.setItem(ACTIVE_PROFILE_KEY, profile); loadLocal(); render(); loadCloud(); }
function accountGate() { return `<main class="account-gate"><section class="account-gate-panel"><div class="brand account-gate-brand"><div class="brand-mark">180</div><div><h1>SpeakUp 180</h1><p>입으로 깨우는 영어</p></div></div><div class="account-gate-copy"><h2>학습 계정을 선택하세요</h2><p>진도는 선택한 계정으로 Supabase에 저장됩니다. 다른 계정으로 잘못 시작하지 않도록 처음에는 반드시 계정을 고르게 했습니다.</p></div><div class="account-choice-grid">${PROFILES.map((p) => `<button class="account-choice" data-initial-profile="${p}"><strong>${p}</strong><span>${p === state.profile ? "최근 사용한 계정 · " : ""}${p}의 학습 진도 불러오기</span></button>`).join("")}</div><p class="account-gate-note">비밀번호 없는 개인용 선택 방식입니다. 공개 서비스로 키우면 로그인 보호를 추가하세요.</p></section></main>`; }
function sidebar() { const nav = [["routine", "루틴 선택", "0"], ["morning", "아침", "1"], ["spare", "자투리", "2"], ["bedtime", "자기 전", "3"], ["focus", "25분 집중", "4"], ["data", "문장 데이터", "5"]]; return `<aside class="sidebar"><div class="brand"><div class="brand-mark">180</div><div><h1>SpeakUp 180</h1><p>입으로 깨우는 영어</p></div></div><nav class="nav">${nav.map(([id, label, n]) => `<button class="nav-button ${state.view === id ? "active" : ""}" data-view="${id}"><span>${label}</span><span>${n}</span></button>`).join("")}</nav><div class="profile-switcher"><span>학습 계정</span><div>${PROFILES.map((p) => `<button class="profile-button ${state.profile === p ? "active" : ""}" data-profile="${p}">${p}</button>`).join("")}</div></div><div class="side-card sync-card"><strong>Supabase 동기화</strong><p>${esc(state.syncStatus)}</p><p>비밀번호 없이 두 프로필을 선택하는 개인용 동기화 방식입니다.</p></div></aside>`; }
function title() { const t = { routine: "오늘은 어떤 루틴으로 들어갈까요?", morning: `아침 루틴 · ${currentDay().title}`, spare: `자투리 시간 · ${currentDay().title}`, bedtime: "자기 전 누적 암송", focus: "25분 모래시계 집중", data: "6개월 문장 데이터 관리" }; return t[state.view] || t.routine; }
function desc() { const d = { routine: "아침에는 오늘 문장을 넣고, 자투리 시간에는 힌트로 꺼내고, 자기 전에는 어제와 오늘을 묶어 기억을 고정합니다.", morning: "오늘 10문장을 5분 동안 소리 내어 읽고, 한글 힌트로 영어 문장을 즉시 떠올립니다.", spare: "이동, 설거지, 산책처럼 짧은 시간에는 한글 힌트 카드만 보고 웅얼거리며 영어로 말해보세요.", bedtime: "자기 전에는 어제와 오늘 문장, 그리고 지난 5일 누적 문장을 빠르게 입으로 복습합니다.", focus: "앱을 켜둔 채 25분 동안 문장 암송에만 몰입하는 모드입니다.", data: "초기 1,800문장 커리큘럼을 제공하고, ChatGPT로 만든 6개월치 JSON 데이터를 가져올 수 있습니다." }; return d[state.view] || d.routine; }
function topbar() { return `<section class="topbar"><div class="title-block"><h2>${esc(title())}</h2><p>${esc(desc())}</p></div><div class="day-picker"><button data-day-step="-1" aria-label="이전 날짜">‹</button><div><label for="dayInput">학습일</label><input id="dayInput" min="1" max="180" type="number" value="${state.day}" /></div><button data-day-step="1" aria-label="다음 날짜">›</button></div></section>`; }
function stats() { const road = Math.round(state.day / 180 * 100), today = Math.round(((doneRead() ? 1 : 0) + recallCount() / 10 + checkedCount() / 10) / 3 * 100); return `<section class="stats-grid">${[["로드맵 진행", `${state.day}/180`, road], ["오늘 완료율", `${today}%`, today], ["암송 체크", `${recallCount()}/10`, recallCount() * 10], ["완료한 날짜", completedCount(), Math.round(completedCount() / 180 * 100)]].map(([a, b, c]) => `<div class="stat"><span>${a}</span><strong>${b}</strong><div class="progress-bar"><div class="progress-fill" style="width:${c}%"></div></div></div>`).join("")}</section>`; }
function routineView() { const start = Math.max(1, state.day - 5); return `<section class="routine-grid"><article class="routine-card primary"><div><span class="routine-kicker">Morning</span><h3>아침 루틴</h3><p>오늘 10문장을 눈으로 보고 5분 동안 소리 내어 읽습니다. 이어서 한글 힌트로 1차 인출까지 끝냅니다.</p></div><div class="routine-meta"><span>오늘 ${state.day}일차</span><span>${doneRead() ? "읽기 완료" : "5분 읽기 대기"}</span></div><button class="primary-button" data-routine-view="morning">아침 루틴 시작</button></article><article class="routine-card"><div><span class="routine-kicker">Small Time</span><h3>자투리 시간</h3><p>영어 원문은 숨기고 한글 힌트 카드만 봅니다. 걷거나 이동할 때 입으로 바로 꺼내는 훈련입니다.</p></div><div class="routine-meta"><span>힌트 카드 10장</span><span>암송 ${recallCount()}/10</span></div><button class="ghost-button" data-routine-view="spare">힌트 카드 열기</button></article><article class="routine-card"><div><span class="routine-kicker">Before Bed</span><h3>자기 전 루틴</h3><p>어제와 오늘을 먼저 확인하고, ${start}일차부터 ${state.day}일차까지 누적 문장을 짧게 훑습니다.</p></div><div class="routine-meta"><span>누적 ${reviewDays().length * 10}문장</span><span>${completedCount()}일 완료</span></div><button class="ghost-button" data-routine-view="bedtime">누적 암송하기</button></article><article class="routine-card compact"><div><span class="routine-kicker">Deep Work</span><h3>25분 집중</h3><p>시간이 확보된 날에는 모래시계 타이머로 오늘 문장과 누적 복습을 묶어 집중합니다.</p></div><button class="ghost-button" data-routine-view="focus">집중 모드</button></article></section>`; }
function sentenceList() { return `<div class="sentence-list">${currentDay().sentences.map((s, i) => `<div class="sentence-row"><div class="sentence-index">${i + 1}</div><div class="sentence-text"><strong>${esc(s.english)}</strong><span>${esc(s.korean)}</span></div><button class="check-button ${isChecked(s.id) ? "done" : ""}" data-check-sentence="${s.id}">${isChecked(s.id) ? "읽음" : "체크"}</button></div>`).join("")}</div>`; }
function timerCard() { return `<div class="timer-card"><div class="timer-display"><div><div class="timer-label">소리 내어 읽기 타이머</div><div class="time">${formatTime(state.read)}</div></div><button class="primary-button" data-read-complete ${state.read > 0 ? "disabled" : ""}>${doneRead() ? "완료됨" : "완료"}</button></div><div class="timer-actions"><button class="ghost-button" data-read-toggle>${state.readRun ? "일시정지" : "시작"}</button><button class="quiet-button" data-read-reset>초기화</button></div><p class="small-note">5분이 끝나면 Recall 단계가 열립니다.</p></div>`; }
function recallCard(spare = false) { const s = currentDay().sentences[state.flash]; return `<div class="card-stack"><button class="flashcard ${spare ? "spare-card" : ""}" data-reveal><div class="meta"><span>${state.flash + 1} / 10 · ${esc(s.level)}</span><span>${state.reveal ? "영어 원문" : "한글 힌트"}</span></div><div class="hint">${esc(s.hint)}</div>${state.reveal ? `<div class="answer">${esc(s.english)}<br><span>${esc(s.korean)}</span></div>` : ""}</button><div class="flash-controls"><button class="ghost-button" data-flash-prev>이전</button><button class="ghost-button" data-flash-next>다음</button><button class="primary-button" data-recall-done="${s.id}">${isRecall(s.id) ? "암송 완료됨" : "암송 완료"}</button><button class="quiet-button" data-reveal>${state.reveal ? "힌트만 보기" : "영어 확인"}</button></div><p class="small-note">카드를 누르면 영어 문장이 나타납니다. 바로 말로 꺼낸 뒤 완료를 눌러주세요.</p></div>`; }
function todaySummary() { return `<div class="panel"><div class="panel-header"><div><h3>오늘의 복습 묶음</h3><p>${Math.max(1, state.day - 5)}일차부터 ${state.day}일차까지 ${reviewDays().length * 10}문장</p></div></div><div class="panel-body"><div class="review-list">${reviewDays().map((d) => `<div class="review-item"><strong>${esc(d.title)}</strong><span>${esc(d.sentences[0].english)}</span></div>`).join("")}</div></div></div>`; }
function morningView() { const complete = state.progress.completedDays.includes(state.day); return `<section class="panel-grid"><div class="panel"><div class="panel-header"><div><h3>아침 3-Step</h3><p>오늘 10문장을 넣고, 한글 힌트로 바로 꺼내는 데까지 진행합니다.</p></div><div class="segmented"><button class="${state.step === "sound" ? "active" : ""}" data-step="sound">Sound On</button><button class="${state.step === "recall" ? "active" : ""}" data-step="recall" ${!doneRead() ? "disabled" : ""}>Recall</button><button class="${state.step === "complete" ? "active" : ""}" data-step="complete" ${recallCount() < 10 ? "disabled" : ""}>Complete</button></div></div><div class="panel-body">${state.step === "sound" ? sentenceList() : state.step === "recall" ? recallCard(false) : `<div class="data-box"><h4>${state.day}일차 마무리</h4><p>오늘 10문장을 모두 한글 힌트로 암송했습니다.</p><div class="input-row"><button class="primary-button" data-complete-day>${complete ? "이미 완료됨" : "오늘 학습 완료"}</button><button class="ghost-button" data-next-day>다음 날짜로 이동</button></div><div class="status-line">${esc(state.status)}</div></div>`}</div></div><div class="card-stack">${timerCard()}${todaySummary()}</div></section>`; }
function spareView() { return `<section class="panel-grid"><div class="panel"><div class="panel-header"><div><h3>한글 힌트 카드</h3><p>짧은 틈에는 힌트를 보자마자 영어 문장을 입으로 꺼냅니다.</p></div><span class="pill">${state.flash + 1} / 10</span></div><div class="panel-body">${recallCard(true)}</div></div><div class="card-stack"><div class="timer-card"><div class="timer-label">자투리 시간 목표</div><div class="mini-goal"><strong>${recallCount()}/10</strong><span>오늘 힌트 카드 암송</span></div><p class="small-note">한 장이라도 입 밖으로 꺼내는 것이 핵심입니다.</p></div>${todaySummary()}</div></section>`; }
function bedtimeView() { const core = state.curriculum.filter((d) => d.day >= Math.max(1, state.day - 1) && d.day <= state.day); return `<section class="panel-grid"><div class="panel"><div class="panel-header"><div><h3>자기 전 핵심 복습</h3><p>어제와 오늘 문장을 먼저 빠르게 말합니다.</p></div><button class="ghost-button" data-export-review>복습 목록 복사</button></div><div class="panel-body"><div class="review-list bedtime-list">${core.flatMap((d) => d.sentences.map((s, i) => `<div class="review-item priority"><strong>${d.day}일차 ${i + 1}. ${esc(s.hint)}</strong><span>${esc(s.english)}</span></div>`)).join("")}</div><div class="status-line">${esc(state.status)}</div></div></div><div class="panel"><div class="panel-header"><div><h3>지난 5일 누적</h3><p>${reviewDays()[0].day}일차부터 ${state.day}일차까지 ${reviewDays().length * 10}문장</p></div></div><div class="panel-body"><div class="review-list">${reviewDays().flatMap((d) => d.sentences.map((s, i) => `<div class="review-item"><strong>${d.day}일차 ${i + 1}. ${esc(s.hint)}</strong><span>${esc(s.english)}</span></div>`)).join("")}</div><p class="small-note">막힌 문장은 내일 아침 다시 입으로 넣습니다.</p></div></div></section>`; }
function focusView() { const p = 1 - state.focus / FOCUS_SECONDS; return `<section class="panel"><div class="panel-body focus-layout"><div><div class="hourglass ${state.focusRun ? "running" : ""}" style="--sand-upper:${Math.max(0, 100 - p * 100)}%; --sand-lower:${Math.min(100, p * 100)}%"><div class="glass"></div><div class="grain"></div></div></div><div class="focus-copy"><h3>${formatTime(state.focus)}</h3><p>25분 동안 오늘 문장과 누적 복습 문장을 입으로 반복합니다.</p><div class="timer-actions"><button class="primary-button" data-focus-toggle>${state.focusRun ? "일시정지" : "집중 시작"}</button><button class="ghost-button" data-focus-reset>초기화</button></div><div class="status-line">${esc(state.status)}</div></div></div></section>`; }
function dataView() { return `<section class="data-grid"><div class="data-box"><h4>저장 방식</h4><p>현재 선택한 계정은 <strong>${esc(state.profile)}</strong>입니다. 진도는 Supabase와 이 기기에 함께 저장됩니다.</p><ul><li>zotinking, viridiansky 두 프로필 동기화</li><li>ChatGPT가 만든 180일 데이터를 붙여넣기</li><li>오디오와 AI 회화는 제외한 MVP</li></ul><div class="input-row"><button class="primary-button" data-export-all>전체 백업 내보내기</button><button class="ghost-button" data-reset-data>기본 1,800문장으로 복구</button></div><div class="status-line">${esc(state.importStatus)}</div></div><div class="data-box"><h4>6개월 문장 데이터 가져오기</h4><textarea id="importText" placeholder="ChatGPT가 만든 JSON을 여기에 붙여넣기"></textarea><div class="input-row"><button class="primary-button" data-import-json>붙여넣은 데이터 적용</button><input class="file-input" id="fileInput" type="file" accept="application/json,.json" /></div></div><div class="data-box"><h4>ChatGPT용 생성 프롬프트</h4><textarea readonly>${esc(chatGptPrompt)}</textarea><div class="input-row"><button class="ghost-button" data-copy-prompt>프롬프트 복사</button></div></div><div class="data-box"><h4>사용법 도움말 이미지</h4><p>아침, 자투리 시간, 자기 전 루틴을 한 장으로 정리했습니다.</p><img class="help-card-preview" src="assets/speakup180-help-card.svg" alt="SpeakUp 180 루틴 도움말"/><div class="input-row"><a class="download-link" href="assets/speakup180-help-card.svg" download>이미지 다운로드</a></div></div></section>`; }
function view() { if (state.view === "morning") return morningView(); if (state.view === "spare") return spareView(); if (state.view === "bedtime") return bedtimeView(); if (state.view === "focus") return focusView(); if (state.view === "data") return dataView(); return routineView(); }
function render() { const app = $("#app"); if (!state.profileReady) { app.innerHTML = accountGate(); bindAccount(); return; } app.innerHTML = `<div class="app-shell">${sidebar()}<main class="main">${topbar()}${stats()}${view()}</main></div>`; bind(); }
function bindAccount() { document.querySelectorAll("[data-initial-profile]").forEach((b) => b.addEventListener("click", () => chooseProfile(b.dataset.initialProfile))); }
function bind() { document.querySelectorAll("[data-view]").forEach((b) => b.addEventListener("click", () => { state.view = b.dataset.view; state.status = ""; render(); })); document.querySelectorAll("[data-routine-view]").forEach((b) => b.addEventListener("click", () => { state.view = b.dataset.routineView; state.status = ""; render(); })); document.querySelectorAll("[data-profile]").forEach((b) => b.addEventListener("click", () => chooseProfile(b.dataset.profile))); document.querySelectorAll("[data-day-step]").forEach((b) => b.addEventListener("click", () => setDay(state.day + Number(b.dataset.dayStep)))); $("#dayInput")?.addEventListener("change", (e) => setDay(e.target.value)); document.querySelectorAll("[data-step]").forEach((b) => b.addEventListener("click", () => { state.step = b.dataset.step; render(); })); document.querySelectorAll("[data-check-sentence]").forEach((b) => b.addEventListener("click", () => toggleChecked(b.dataset.checkSentence))); document.querySelectorAll("[data-reveal]").forEach((b) => b.addEventListener("click", () => { state.reveal = !state.reveal; render(); })); $("[data-flash-prev]")?.addEventListener("click", () => moveFlash(-1)); $("[data-flash-next]")?.addEventListener("click", () => moveFlash(1)); $("[data-recall-done]")?.addEventListener("click", (e) => markRecall(e.currentTarget.dataset.recallDone)); $("[data-read-toggle]")?.addEventListener("click", toggleRead); $("[data-read-reset]")?.addEventListener("click", resetRead); $("[data-read-complete]")?.addEventListener("click", completeRead); $("[data-complete-day]")?.addEventListener("click", completeDay); $("[data-next-day]")?.addEventListener("click", () => setDay(state.day + 1)); $("[data-export-review]")?.addEventListener("click", copyReview); $("[data-focus-toggle]")?.addEventListener("click", toggleFocus); $("[data-focus-reset]")?.addEventListener("click", resetFocus); $("[data-export-all]")?.addEventListener("click", exportAll); $("[data-reset-data]")?.addEventListener("click", resetData); $("[data-import-json]")?.addEventListener("click", importText); $("[data-copy-prompt]")?.addEventListener("click", copyPrompt); $("#fileInput")?.addEventListener("change", importFile); }
function setDay(d) { state.day = clamp(d, 1, 180); state.flash = 0; state.reveal = false; state.step = doneRead() ? "recall" : "sound"; state.read = doneRead() ? 0 : READ_SECONDS; saveLocal(); render(); }
function toggleChecked(id) { const k = dayKey(), set = new Set(state.progress.checkedSentences[k] || []); set.has(id) ? set.delete(id) : set.add(id); state.progress.checkedSentences[k] = [...set]; saveLocal(); render(); }
function moveFlash(n) { state.flash = clamp(state.flash + n, 0, 9); state.reveal = false; render(); }
function markRecall(id) { const k = dayKey(), set = new Set(state.progress.recallDone[k] || []); set.add(id); state.progress.recallDone[k] = [...set]; if (state.flash < 9) state.flash += 1; if (set.size >= 10) state.step = "complete"; state.reveal = false; saveLocal(); render(); }
function toggleRead() { state.readRun = !state.readRun; clearInterval(readTimer); if (state.readRun) readTimer = setInterval(() => { state.read = Math.max(0, state.read - 1); if (!state.read) { state.readRun = false; clearInterval(readTimer); } render(); }, 1000); render(); }
function resetRead() { clearInterval(readTimer); state.readRun = false; state.read = READ_SECONDS; delete state.progress.readDone[dayKey()]; saveLocal(); render(); }
function completeRead() { state.progress.readDone[dayKey()] = true; state.read = 0; state.step = "recall"; saveLocal(); render(); }
function completeDay() { state.progress.completedDays = [...new Set([...state.progress.completedDays, state.day])].sort((a, b) => a - b); state.status = `${state.day}일차가 완료되었습니다.`; saveLocal(); render(); }
function toggleFocus() { state.focusRun = !state.focusRun; clearInterval(focusTimer); if (state.focusRun) focusTimer = setInterval(() => { state.focus = Math.max(0, state.focus - 1); if (!state.focus) { state.focusRun = false; state.status = "25분 집중 세션이 끝났습니다."; clearInterval(focusTimer); } render(); }, 1000); render(); }
function resetFocus() { clearInterval(focusTimer); state.focusRun = false; state.focus = FOCUS_SECONDS; state.status = ""; render(); }
function copyReview() { const text = reviewDays().map((d) => `[${d.title}]\n` + d.sentences.map((s, i) => `${i + 1}. ${s.hint}\n   ${s.english}`).join("\n")).join("\n\n"); navigator.clipboard.writeText(text); state.status = "복습 목록을 클립보드에 복사했습니다."; render(); }
function exportAll() { const payload = { exportedAt: new Date().toISOString(), app: "SpeakUp 180", profile: state.profile, progress: { day: state.day, ...state.progress }, curriculum: { version: "1.0", days: state.curriculum } }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `speakup-180-${state.profile}-backup-day-${state.day}.json`; a.click(); URL.revokeObjectURL(a.href); }
function resetData() { localStorage.removeItem(profileKey(CUSTOM_DATA_KEY)); state.curriculum = buildCurriculum(); state.importStatus = "기본 1,800문장으로 복구했습니다."; saveCurriculumCloud(); render(); }
function applyImport(data) { const normalized = validateCurriculum(data?.curriculum || data); if (!normalized) { state.importStatus = "가져오기 실패: 180일 x 하루 10문장 JSON 형식을 확인해주세요."; render(); return; } state.curriculum = normalized; localStorage.setItem(profileKey(CUSTOM_DATA_KEY), JSON.stringify({ days: normalized })); state.importStatus = "새 6개월 문장 데이터를 적용했습니다."; saveCurriculumCloud(); render(); }
function importText() { applyImport(safe($("#importText")?.value)); }
function importFile(e) { const file = e.target.files?.[0]; if (!file) return; const r = new FileReader(); r.onload = () => applyImport(safe(String(r.result))); r.readAsText(file); }
function copyPrompt() { navigator.clipboard.writeText(chatGptPrompt); state.importStatus = "ChatGPT용 프롬프트를 복사했습니다."; render(); }
render();
